# Generated by Django 5.0.6 on 2024-07-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
